// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use bigdecimal::BigDecimal;
use chrono::NaiveDateTime;

#[derive(Queryable, Debug)]
#[diesel(table_name = game_events)]
pub struct GameEvent {
    pub id: i64,
    pub session_id: Option<i64>,
    pub provider_id: Option<i64>,
    pub game_id: Option<i64>,
    pub user_id: Option<i64>,
    pub currency: Option<i64>,
    pub spin_id: Option<i64>,
    pub balance_before: Option<BigDecimal>,
    pub balance_after: Option<BigDecimal>,
    pub bet: Option<BigDecimal>,
    pub win: Option<BigDecimal>,
    pub profit: Option<BigDecimal>,
    pub transaction_create_time: NaiveDateTime,
    pub transaction_finished_time: NaiveDateTime,
}

#[derive(Queryable, Debug)]
#[diesel(table_name = game_sessions)]
pub struct GameSession {
    pub id: i64,
    pub session_id: Option<i64>,
    pub user_id: Option<i64>,
    pub game_id: Option<i64>,
    pub currency: Option<i64>,
    pub start_time: NaiveDateTime,
}

#[derive(Queryable, Debug)]
#[diesel(table_name = games)]
pub struct Game {
    pub id: i32,
    pub provider_id: i32,
    pub code: String,
    pub name: String,
    pub image: String,
    pub is_mobile: bool,
    pub is_desktop: bool,
    pub is_tablet: bool,
    pub is_demo: bool,
    pub is_embedded: bool,
    pub bonus: i32,
    pub free_spins: i32,
    pub is_active: bool,
    pub created_at: NaiveDateTime,
    pub updated_at: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
#[diesel(table_name = providers)]
pub struct Provider {
    pub id: i32,
    pub name: String,
    pub aggregator: String,
    pub created_at: NaiveDateTime,
    pub updated_at: Option<NaiveDateTime>,
}

